# Creating NumPy Arrays

## Creating 1 dimensional array

In [3]:
import numpy as np
num_list = [10,12,14,16,18,20]
num_array = np.array(num_list)
print(num_array)

[10 12 14 16 18 20]


## Creating 2 dimensional array

In [4]:
row1 = [10,11,12]
row2 = [45,32,16]
row3 = [45,23,16]
num_array2d = np.array([row1,row2,row3])
print(num_array2d)

[[10 11 12]
 [45 32 16]
 [45 23 16]]


In [5]:
num_array2d.shape

(3, 3)

In [6]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [11]:
a1 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [15]:
print(a1[0])

[1 2 3 4]


In [16]:
print(a1[2])

[ 9 10 11 12]


In [17]:
a2=np.ones(2)
print(a2)

[1. 1.]


# How to create a basic array
This section covers np.array(), np.zeros(), np.ones(), np.empty(), np.arange(), np.linspace(), dtype



In [18]:
b1 = np.array([1,2,3,4,5,6,7,8,9,])
print(b1)

[1 2 3 4 5 6 7 8 9]


In [24]:
import numpy as np
b0 = np.zeros(6)  # Creating an numpy array of 6 with 0's
print(b0)

[0. 0. 0. 0. 0. 0.]


In [25]:
bemp = np.empty(2)
print(bemp)

[0. 0.]


# bones = np.ones(6)
print(bones)

In [28]:
barrange1 =np.arange(20)
print(barrange1)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [27]:
barrange =np.arange(10,20,2)
print(barrange)

[10 12 14 16 18]


In [30]:
blinespce = np.linspace(0,20,num=5)
print(blinespce)

[ 0.  5. 10. 15. 20.]


In [32]:
btype = np.ones(6,dtype=np.int64)
print(btype)

[1 1 1 1 1 1]


# Adding, removing, and sorting elements
This section covers np.sort(), np.concatenate()

In [35]:
cnpar = np.array([7,3,7,8,9])
np.sort(cnpar)

array([3, 7, 7, 8, 9])

In [40]:
npar1 = np.array([1,2,3,4,5])
npar2 = np.array([7,8,9,11,12])
npar3 = np.concatenate((npar1,npar2))  # Note 2 brackets are needed to contenate
print(npar3)

[ 1  2  3  4  5  7  8  9 11 12]


# How do you know the shape and size of an array?
This section covers ndarray.ndim, ndarray.size, ndarray.shape



In [41]:
print(cnpar.size) # cnpar is defined in defined few lines above 

5


In [42]:
print(cnpar.shape) # cnpar is defined in defined few lines above 

(5,)


In [44]:
array_ex_size_shape = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(array_ex_size_shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [45]:
print(array_ex_size_shape.size)

9


In [46]:
print(array_ex_size_shape.shape)

(3, 3)


In [52]:
threed_array_ex_size_shape = np.array([
                                   [[10,20,30],[40,50,60],[70,80,90]],
                                   [[10,11,12],[13,14,15],[16,17,18]],
                                   [[19,20,21],[22,23,24],[25,26,27]]
                                 ])

In [53]:
print(threed_array_ex_size_shape)


[[[10 20 30]
  [40 50 60]
  [70 80 90]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


In [54]:
print(threed_array_ex_size_shape.size)

27


In [55]:
print(threed_array_ex_size_shape.shape)

(3, 3, 3)


# Can you reshape an array?
This section covers arr.reshape()

In [58]:
arrray_reshape = np.arange(1,10,1)
print(arrray_reshape)

[1 2 3 4 5 6 7 8 9]


In [76]:
array_reshaped = arrray_reshare.reshape(3,3)

In [63]:
print(array_reshaped)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [64]:
arrray_reshape1 = np.arange(1,7,1)
print(arrray_reshape1)

[1 2 3 4 5 6]


In [71]:
arrray_reshaped1 = arrray_reshape1.reshape(3,2)
print(arrray_reshaped1)

[[1 2]
 [3 4]
 [5 6]]


In [72]:
print(arrray_reshaped1.shape)

(3, 2)


In [74]:
arrray_reshape2 = np.arange(1,7,1)
print(arrray_reshape2)
arrray_reshaped2 = arrray_reshape2.reshape(2,3)
print(arrray_reshaped1)
print(arrray_reshaped2.shape)

[1 2 3 4 5 6]
[[1 2]
 [3 4]
 [5 6]]
(2, 3)


## Reshaping array

# numpy.reshape(a, newshape=(1, 6), order='C')  ,  C-like order 

In [78]:
np.reshape(arrray_reshape2, newshape=(1, 6), order='C')

array([[1, 2, 3, 4, 5, 6]])